services:
  transfer-app:
    build:
      context: ../apps/transfer-app
      dockerfile: Dockerfile
    container_name: transfer-app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=transfer
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci
    ports:
      - "8080:8080"
    depends_on:
      - transfer-db

  transfer-db:
    image: mysql:8.0.32
    container_name: transfer-db
    ports:
      - "3306:3306"

  wallet-app:
    build:
      context: ../apps/wallet-app
      dockerfile: Dockerfile
    container_name: wallet-app
    ports:
      - "8081:8080"
    depends_on:
      - wallet-db-1
      - wallet-db-2

  wallet-db-1:
    image: mysql:8.0.32
    container_name: wallet-db-1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=wallet
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci
    ports:
      - "3307:3306"

  wallet-db-2:
    image: mysql:8.0.32
    container_name: wallet-db-2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=wallet
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci
    ports:
      - "3308:3306"
